# 1. Repaso de Python

## 1.1 IPython y derivados

In [1]:
3+123

126

### Buscando ayuda

In [2]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
?len

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


In [4]:
L = [4, 2, 5]

In [5]:
?L.insert

Signature: L.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method


In [6]:
def cuadrado(x):
    """Eleva x al cuadrado."""
    return x*x

In [7]:
cuadrado(15)

225

In [8]:
?cuadrado

Signature: cuadrado(x)
Docstring: Eleva x al cuadrado.
File:      /tmp/ipykernel_5887/2903879269.py
Type:      function


In [9]:
??cuadrado

Signature: cuadrado(x)
Source:   
def cuadrado(x):
    """Eleva x al cuadrado."""
    return x*x
File:      /tmp/ipykernel_5887/2903879269.py
Type:      function


In [10]:
??len

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


### Autocompletado

In [11]:
L = [3, 5, 7]

Al escribir `L.` segudo del botón de tabulación surge un menún de autocompletado.

In [12]:
L.reverse

<function list.reverse()>

In [13]:
i = 2
obj = "X"
L.insert(i, obj)

In [14]:
L

[3, 5, 'X', 7]

In [15]:
from math import comb

In [16]:
?comb

Signature: comb(n, k, /)
Docstring:
Number of ways to choose k items from n items without repetition and without order.

Evaluates to n! / (k! * (n - k)!) when k <= n and evaluates
to zero when k > n.

Also called the binomial coefficient because it is equivalent
to the coefficient of k-th term in polynomial expansion of the
expression (1 + x)**n.

Raises TypeError if either of the arguments are not integers.
Raises ValueError if either of the arguments are negative.
Type:      builtin_function_or_method


In [17]:
import sys

In [18]:
sys.*ver*?

sys.api_version
sys.hexversion
sys.version
sys.version_info

### Métodos mágicos de IPython

In [19]:
%%timeit
L = []
for n in range(10_000):
    L.append(n**2)

2.83 ms ± 347 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%%timeit
L = [n**2 for n in range(10_000)]

2.27 ms ± 34.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Input y Output como historial

In [23]:
Out[12]

<function list.reverse()>

In [24]:
In[12]

'L.reverse'

### Depuración

In [25]:
def dividir(a, b):
    return a/b

In [26]:
def func(x):
    a = x
    b = x - 1
    return dividir(a, b)

In [27]:
func(1)

ZeroDivisionError: division by zero

In [29]:
%debug

> /tmp/ipykernel_5887/1740857772.py(2)dividir()
      1 def dividir(a, b):
----> 2     return a/b



ipdb>  help



Documented commands (type help <topic>):
EOF    commands   enable    ll        pp       s                until 
a      condition  exit      longlist  psource  skip_hidden      up    
alias  cont       h         n         q        skip_predicates  w     
args   context    help      next      quit     source           whatis
b      continue   ignore    p         r        step             where 
break  d          interact  pdef      restart  tbreak         
bt     debug      j         pdoc      return   u              
c      disable    jump      pfile     retval   unalias        
cl     display    l         pinfo     run      undisplay      
clear  down       list      pinfo2    rv       unt            

Miscellaneous help topics:
exec  pdb



ipdb>  print(a)


1


ipdb>  print(b)


0


ipdb>  up


> /tmp/ipykernel_5887/2440189193.py(4)func()
      1 def func(x):
      2     a = x
      3     b = x - 1
----> 4     return dividir(a, b)



ipdb>  print(x)


1


ipdb>  print(b)


0


ipdb>  quit


## 1.2 Uso de Numpy

### Los tipos de datos en Python

In [30]:
type(13487)

int

In [32]:
f"{13487:b}"

'11010010101111'

In [31]:
type("Hola")

str

In [33]:
[123,513,13515]

[123, 513, 13515]

In [35]:
import numpy as np  # Por tradición así se importa

In [38]:
A = np.array([3.14, 4, 2, 3])

In [39]:
A

array([3.14, 4.  , 2.  , 3.  ])

In [40]:
A.dtype

dtype('float64')

In [41]:
4*64

256

In [42]:
A = np.array([3.14, 4, 2, 3], np.float16)

In [43]:
A

array([3.14, 4.  , 2.  , 3.  ], dtype=float16)

In [45]:
L = [[1, 3, 41], [135,53,35], [4, 5, 6]]

In [46]:
L

[[1, 3, 41], [135, 53, 35], [4, 5, 6]]

In [47]:
L[0]

[1, 3, 41]

In [48]:
L[1]

[135, 53, 35]

In [49]:
L[1][0]

135

In [51]:
np.array([[1, 3, 41], [135, 53, 35], [4, 5, 6]], dtype=np.int16)

array([[  1,   3,  41],
       [135,  53,  35],
       [  4,   5,   6]], dtype=int16)

In [52]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.zeros((10, 10), dtype=np.int_)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [58]:
np.bool_

numpy.bool_

In [59]:
np.complex64

numpy.complex64